export const ACTIONS = {
  ADD_REGEX: "ADD_REGEX",
  EDIT_REGEX: "EDIT_REGEX",
  DELETE_REGEX: "DELETE_REGEX",
  APPROVE_REGEX: "APPROVE_REGEX",
  SET_MODE: "SET_MODE",
  SELECT_PATTERN: "SELECT_PATTERN",
  SET_TEXT: "SET_TEXT",
} as const;
